### ISSUE TITLE
Run plone.restapi performance tests on jenkins.plone.org

### ISSUE THREAD

**Issue by tisto** [plone/jenkins.plone.org#215]
I set up the plone.restapi performance tests on our kitconcept Jenkins. Though, I think it would make more sense to run them on jenkins.plone.org to allow other people to work with it as well. Here is what we need:

- [x] Install JMeter 3.x on our Nodes (just wget http://www-eu.apache.org/dist//jmeter/binaries/apache-jmeter-3.3.tgz, move it to /opt/jenkins and chown to Jenkins user)
- [x] Install latest Jenkins Pipeline plugins on Jenkins
- [x] Install Jenkins Performance plugin on Jenkins https://wiki.jenkins.io/display/JENKINS/Performance+Plugin

@gforcada wanna help out? :)

When we have the latest Jenkins pipeline plugin installed, writing a declarative pipeline job for coredev is a piece of cake.

**Comment by gforcada** [comment]
@tisto yes, I can help out on that, as I don't want to install that manually, if you can provide the pull requests on the ansible jobs that would make things quicker.  Maybe there's already a ansible playbook that installs jmeter..

**Comment by tisto** [comment]
@gforcada awesome. Here is our ansible snipped to install JMeter:

```
---
- file:
    path: /opt/jmeter
    state: directory
    owner: kitconcept
    group: kitconcept

- name: Install jMeter
  unarchive:
    src: http://www-eu.apache.org/dist/jmeter/binaries/apache-jmeter-3.3.tgz
    extra_opts: [--strip-components=1]
    remote_src: yes
    dest: /opt/jmeter
    owner: kitconcept

- name: Create jmeter bin
  file:
    src: /opt/jmeter/bin/jmeter
    dest: /usr/local/bin/jmeter
    owner: kitconcept
    group: kitconcept
    state: link
```

We also need to update jenkins-job-builder to support Jenkinsfile pipeline as code:

https://docs.openstack.org/infra/jenkins-job-builder/project_pipeline.html
